version: "3"
services:
  minio:
    # 镜像文件
    image: ${te.storage.minio.image}
    container_name: minio-server
    ports:
      - ${te.storage.minio.port}:9000
    volumes: 
      - "${te.storage.minio.volumeBasePath}:/data"
    environment:
      MINIO_ACCESS_KEY: ${te.storage.minio.accessKey}
      MINIO_SECRET_KEY: ${te.storage.minio.secretKey}
    command: server /data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"