dataBasePath: /mnt/data_disk_10000/docker-volume
dockerBuildDataPath: /mnt/data_disk_10000/deploy/docker-build-data

module:
  start:
    name: module-start
    volumeBasePath: ${dataBasePath}/${app.name}-module-start
    port:
      - node: 8081
        container: 8081

redis:
  name: redis
  image: redis
  host: 127.0.0.1
  port:
    node: 36379
    container: 6379
  volumeBasePath: ${dataBasePath}/redis
  # 相当于密码
  password: QWER@1234

mysql:
  name: mysql
  ip: 127.0.0.1
  port:
    node: 33306
    container: 3306
  volumeBasePath: ${dataBasePath}/mysql
  username: root
  password: QWER@1234

# 文件存储配置
storage:
  enable: true
  type: minio
  url:
    # url过期时间单位是s,用于具有时效性的链接
    expiryTime: 60
    # 内网url http://work01.server.com
    int: http://work01.server.com:9090/files/
    # 外网 url http://47.78.12.56
    # 这里以 work01.server.com 当做外网测试
    ext: http://work01.server.com:39000/files
  minio:
    image: minio/minio:RELEASE.2021-06-14T01-29-23Z
    accessKey: minioadmino
    secretKey: minioadmino
    volumeBasePath: ${dataBasePath}/minio
    ip: 192.168.137.128
    port: 39000
  oss:
    secretAccessKey: asdq3e4q3
    accessKeyId: qwerqwerwer
    endpoint: fcgdfgdfg
    # 是否使能代理，如果使能nginx代理，则获取持久链接的前缀
    # 就是url中的lan或者wan作为前缀
    proxy:
      enable: false
